version: '3'

services:
  semanticapi:
    build: . 
    container_name: semanticapi
    ports:
      # The HTTP port
      - "8099:80"
      - "8098:8080"
    environment:
      - DEBUG_DISABLE=${DEBUG_DISABLE}
      - DEBUG_LEVEL=${DEBUG_LEVEL}
      - "SOLR"
      - "base_url"
      - "forbiddenfields"
      - "skosmosendpoint"
      - "CVfields"
      - "querytemplate"
      - "strict_lookup"
    volumes:
      - ./data:/tmp
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
